using ECommerce.Application.Common;
using ECommerce.Application.Common.Behavior;
using ECommerce.Infrastructure.BackgroundJobs;
using ECommerce.Infrastructure.Extensions;
using FluentValidation;
using MediatR;
using StackExchange.Redis;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container
builder.Services.AddControllers();

// Swagger
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    // Include XML comments (generated by project) if available
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
    {
        options.IncludeXmlComments(xmlPath);
    }
});

// Infrastructure
DependencyInjection.AddInfrastructure(
    builder.Services,
    builder.Configuration
);

// Background Service
builder.Services.AddHostedService<CartReminderBackgroundService>();
builder.Services.AddHostedService<CartCleanupBackgroundService>();
builder.Services.AddHostedService<InvoiceBackgroundService>();
builder.Services.AddHostedService<ProductViewBackgroundService>();

//Memory Cache
builder.Services.AddMemoryCache();

// Validation Behavior
builder.Services.AddTransient(
    typeof(IPipelineBehavior<,>),
    typeof(ValidationBehavior<,>)
);
//  Redis
builder.Services.AddSingleton<IConnectionMultiplexer>(
    ConnectionMultiplexer.Connect(
        builder.Configuration.GetConnectionString("Redis")!));

// MediatR
builder.Services.AddMediatR(cfg =>
    cfg.RegisterServicesFromAssembly(
        typeof(ApplicationAssemblyMarker).Assembly));

// FluentValidation
builder.Services.AddValidatorsFromAssembly(
    typeof(ApplicationAssemblyMarker).Assembly);

var app = builder.Build();

// Swagger Middleware
app.UseSwagger();
app.UseSwaggerUI();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();