<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerece.Domain\ECommerece.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Exception\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Features\Order\Query\GeOrdertById\GeOrdertByIdQuery.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extensions.FluentValidation.Br" Version="1.0.2" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

</Project>

